name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up C environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: make check
      run: make check
    - name: make examples
      run: make examples
